# Generated by Django 5.0.2 on 2024-02-19 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=100)),
                ('age', models.IntegerField(null=True)),
                ('status', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('first_login', models.DateTimeField(auto_now=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('published', models.BooleanField(default=False)),
                ('published_date', models.DateTimeField(auto_now=True)),
                ('cooking_time', models.IntegerField(null=True)),
                ('cook_process', models.TextField()),
                ('amount_of_servings', models.IntegerField(null=True)),
                ('likes', models.IntegerField(null=True)),
                ('calories', models.IntegerField(null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.user')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('comment_date', models.DateTimeField(auto_now=True)),
                ('published', models.BooleanField(default=False)),
                ('comment_recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipe')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.user')),
            ],
        ),
    ]
